name: Node CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Linting (prettier)
        uses: actions/setup-node@v1
        with: 
          node-version: '15.x'
      - run: npm install
      - run: npm run check
      - run: npm run lint
  
      # TODO: add tests
