name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm check
      - run: pnpm lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm test

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm build
      - name: Verify entry point
        run: test -f dist/index.js
